name: ttt_sidekick
description: Sidekick CLI for ttt
version: 0.0.1
publish_to: none

environment:
  sdk: '>=2.12.0 <3.0.0'

executables:
  ttt: ttt

dependencies:
  args: ^2.3.0
  csv: ^5.0.0
  dcli: ^1.16.0
  intl: ^0.17.0
  sidekick_core: ^0.3.2
  timeago: ^3.0.2


dev_dependencies:
  lint: ^1.5.3
